### ISSUE TITLE
Is this compatible with Elm 0.18?

### ISSUE THREAD

**Issue by kgashok** [marcosh/elm-html-to-unicode#1]

**Comment by marcosh** [comment]
@kgashok yes, it is. Version 1.0.2 works on elm 0.18

**Comment by kgashok** [comment]
It works in Elm 0.18, thanks! 
The **\t** and **\\"** don't get converted. Any particular reason?

**Comment by marcosh** [comment]
I will check on that.

Could you please create a pull request just with a failing test?

**Comment by kgashok** [comment]
For the following incoming text (The back slash of the **quote** is not displayed - edit the comment to see the actual text): 

text = "A:\tA reasonable computer ought to give you transparent access to \tall available memory. If you&#39;re not so lucky, you&#39;ll either \thave to rethink your program&#39;s use of memory, or use various \tsystem-specific techniques. \t64K is (still) a pretty big chunk of memory. No matter how much \tmemory your computer has available, it&#39;s asking a lot to be able \tto allocate huge amounts of it contiguously. (The C Standard \tdoes not guarantee that single objects can be 32K or larger, \tor 64K for C99.) Often it&#39;s a good idea to use data \tstructures which don&#39;t require that all memory be contiguous. \tFor dynamically-allocated multidimensional arrays, you can \tuse pointers to pointers, as illustrated in question 6.16. \tInstead of a large array of structures, you can use a linked \tlist, or an array of pointers to structures. \tIf you&#39;re using a PC-compatible (8086-based) system, and running \tup against a 64K or 640K limit, consider using &quot;huge&quot; memory \tmodel, or expanded or extended memory, or malloc variants such \tas halloc() or farmalloc(), or a 32-bit &quot;flat&quot; compiler (e.g. \tdjgpp, see question 18.3), or some kind of a DOS extender, or \tanother operating system. \tReferences: ISO Sec. 5.2.4.1; C9X Sec. 5.2.4.1. 19.24:\tWhat does the error message &quot;DGROUP data allocation exceeds 64K&quot; \tmean, and what can I do about it? I thought that using large \tmodel meant that I could use more than 64K of data! A:\tEven in large memory models, MS-DOS compilers apparently toss \tcertain data (strings, some initialized global or static \tvariables) into a default data segment, and it&#39;s this segment \tthat is overflowing. Either use less global data, or, if you&#39;re \talready limiting yourself to reasonable amounts (and if the \tproblem is due to something like the number of strings), you may \tbe able to coax the compiler into not using the default data \tsegment for so much. Some compilers place only &quot;small&quot; data \tobjects in the default data segment, and give you a way (e.g. \tthe /Gt option under Microsoft compilers) to configure the \tthreshold for &quot;small.&quot; 19.25:\tHow can I access memory (a memory-mapped device, or graphics"


I get the following output: 

<p> 
"A:\tA reasonable computer ought to give you transparent access to \tall available memory. If you're not so lucky, you'll either \thave to rethink your program's use of memory, or use various \tsystem-specific techniques. \t64K is (still) a pretty big chunk of memory. No matter how much \tmemory your computer has available, it's asking a lot to be able \tto allocate huge amounts of it contiguously. (The C Standard \tdoes not guarantee that single objects can be 32K or larger, \tor 64K for C99.) Often it's a good idea to use data \tstructures which don't require that all memory be contiguous. \tFor dynamically-allocated multidimensional arrays, you can \tuse pointers to pointers, as illustrated in question 6.16. \tInstead of a large array of structures, you can use a linked \tlist, or an array of pointers to structures. \tIf you're using a PC-compatible (8086-based) system, and running \tup against a 64K or 640K limit, consider using \"huge\" memory \tmodel, or expanded or extended memory, or malloc variants such \tas halloc() or farmalloc(), or a 32-bit \"flat\" compiler (e.g. \tdjgpp, see question 18.3), or some kind of a DOS extender, or \tanother operating system. \tReferences: ISO Sec. 5.2.4.1; C9X Sec. 5.2.4.1. 19.24:\tWhat does the error message \"DGROUP data allocation exceeds 64K\" \tmean, and what can I do about it? I thought that using large \tmodel meant that I could use more than 64K of data! A:\tEven in large memory models, MS-DOS compilers apparently toss \tcertain data (strings, some initialized global or static \tvariables) into a default data segment, and it's this segment \tthat is overflowing. Either use less global data, or, if you're \talready limiting yourself to reasonable amounts (and if the \tproblem is due to something like the number of strings), you may \tbe able to coax the compiler into not using the default data \tsegment for so much. Some compilers place only \"small\" data \tobjects in the default data segment, and give you a way (e.g. \tthe /Gt option under Microsoft compilers) to configure the \tthreshold for \"small.\" 19.25:\tHow can I access memory (a memory-mapped device, or graphics"
</p>

The expected output is: 

A: A reasonable computer ought to give you transparent access to all available memory. If you're not so lucky, you'll either have to rethink your program's use of memory, or use various system-specific techniques. 64K is (still) a pretty big chunk of memory. No matter how much memory your computer has available, it's asking a lot to be able to allocate huge amounts of it contiguously. (The C Standard does not guarantee that single objects can be 32K or larger, or 64K for C99.) Often it's a good idea to use data structures which don't require that all memory be contiguous. For dynamically-allocated multidimensional arrays, you can use pointers to pointers, as illustrated in question 6.16. Instead of a large array of structures, you can use a linked list, or an array of pointers to structures. If you're using a PC-compatible (8086-based) system, and running up against a 64K or 640K limit, consider using "huge" memory model, or expanded or extended memory, or malloc variants such as halloc() or farmalloc(), or a 32-bit "flat" compiler (e.g. djgpp, see question 18.3), or some kind of a DOS extender, or another operating system. References: ISO Sec. 5.2.4.1; C9X Sec. 5.2.4.1. 19.24: What does the error message "DGROUP data allocation exceeds 64K" mean, and what can I do about it? I thought that using large model meant that I could use more than 64K of data! A: Even in large memory models, MS-DOS compilers apparently toss certain data (strings, some initialized global or static variables) into a default data segment, and it's this segment that is overflowing. Either use less global data, or, if you're already limiting yourself to reasonable amounts (and if the problem is due to something like the number of strings), you may be able to coax the compiler into not using the default data segment for so much. Some compilers place only "small" data objects in the default data segment, and give you a way (e.g. the /Gt option under Microsoft compilers) to configure the threshold for "small." 19.25: How can I access memory (a memory-mapped device, or graphics

**Comment by kgashok** [comment]
Just curious: Where is this function `convertChars` defined? https://github.com/marcosh/elm-html-to-unicode/blob/master/src/ElmEscapeHtml.elm#L47

**Comment by marcosh** [comment]
`convertChars` there is the first argument of the function, that is used in `escape` and `unescape` above

**Comment by kgashok** [comment]
BTW, I am unable to do a pull request - is my text snippet sufficient?

**Comment by marcosh** [comment]
@kgashok I had a look around and I realized that actually the library should work as it does now.

The `unescape` function that you are using converts characters from html encoding to Unicode. Html encoding has all the characters in the `&...;` format, hence `\t` and `\"` should not be converted.

To use my library, you should encode `\t` as `&#9;` and `\"` as `&#34;`

**Comment by kgashok** [comment]
@marcosh My bad! I actually was using `toString` to display the contents of the String in a HTML `div`. Now I have used `text` and everything is working as expected. Sorry for the bother!
